# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'Parse'
pod 'Charts'
pod 'Mapbox-iOS-SDK'

target 'Beto' do

end

target 'BetoTests' do

end

target 'BetoUITests' do

end
